import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./component/shared/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Poppins } from "next/font/google";
import Footer from "./component/shared/footer/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[poppins]`}
        
      >
       
        <Header></Header>
        {children}
        <Footer></Footer>

      </body>
    </html>
  );
}
